Repository NativeScript/nativescript-plugin-seed, pull requests merged in 2019-05, with the labels that each got.

#131 feat: add default values to postclone prompts if it is executed on non interactive environment and fix typo in script args
  seed-tests/postclone.tests.js
  seed-tests/tests.utils.js
  src/scripts/postclone.js
Labels: cla: yes, new PR

#132 Resolve issue with travis build for plugins after postclone is executed
  src/.travis.yml
  src/package.json
Labels: new PR

#133 fix: remove deleted script
  src/.travis.yml
Labels: cla: yes, new PR

#136 Remove ambiguos sentence in Readme.md
  README.md
Labels: new PR

#137 chore: update to 5.4
  src/package.json
Labels: cla: yes, new PR

#138 chore: update travis configuration for new seed structure
  .travis.yml
Labels: cla: yes, new PR

#141 fix: remove not required predefined configuration from tsconfig
  seed-tests/postclone.tests.js
  src/scripts/postclone.js
Labels: cla: yes

#145 chore: update travis to node 10
  .travis.yml
  src/.travis.yml
Labels: cla: yes
